MVCOnlineTicariOtomasyon/Controllers/FaturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCOnlineTicariOtomasyon.Models.Sınıflar;

namespace MVCOnlineTicariOtomasyon.Controllers
{
    public class FaturaController : Controller
    {
        Context c = new Context();
        // GET: Fatura
        public ActionResult Index()
        {
            var liste = c.Faturalars.ToList();
            return View(liste);
        }
        [HttpGet]
        public ActionResult FaturaEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult FaturaEkle(Faturalar f)
        {
            c.Faturalars.Add(f);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult FaturaGetir(int id) 
        {
            var deger = c.Faturalars.Find(id);
            return View("FaturaGetir", deger);
        }
        public ActionResult FaturaGuncelle(Faturalar f)
        {
            var deger = c.Faturalars.Find(f.FaturaID);
            deger.FaturaSeriNo = f.FaturaSeriNo;
            deger.FaturaSıraNo = f.FaturaSıraNo;
            deger.FaturaTarih = f.FaturaTarih;
            deger.Saat = f.Saat;
            deger.TeslimAlan = f.TeslimAlan;
            deger.TeslimEden = f.TeslimEden;
            deger.VergiDairesi = f.VergiDairesi;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult FaturaDetay(int id)
        {
            var deger = c.FaturaKalems.Where(x => x.FaturaID == id).ToList();
            return View(deger);
        }
         [HttpGet]
        public ActionResult YeniKalem()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniKalem(FaturaKalem f)
        {
            c.FaturaKalems.Add(f);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVCOnlineTicariOtomasyon/Views/Fatura/FaturaDetay.cshtml
@using MVCOnlineTicariOtomasyon.Models.Sınıflar;
@model List<FaturaKalem> 
@{
    ViewBag.Title = "FaturaDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    body {
        background-color: darkgray
    }
</style>
<br />
<h2>Fatura Detay Sayfası</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active"></li>
</ol>
<br />
<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Açıklama</th>
        <th>Miktar</th>
        <th>Birim Fiyat</th>
        <th>Tutar</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.FaturaKalenID</td>
            <td>@x.Aciklama</td>
            <td>@x.Miktar</td>
            <td>@x.BirimFiyat</td>
            <td>@x.Tutar</td>
        </tr>
    }
</table>

<a href="/Fatura/YeniKalem" class="btn btn-default" style="background-color:darksalmon">Yeni Kalem Girişi</a>

MVCOnlineTicariOtomasyon/Views/Fatura/FaturaEkle.cshtml
@model MVCOnlineTicariOtomasyon.Models.Sınıflar.Faturalar
@{
    ViewBag.Title = "FaturaEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    body {
        background-color: darkgray
    }
</style>
<br />
<h2>Yeni Fatura Ekleme Alanı</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.FaturaSeriNo)
    @Html.TextBoxFor(x => x.FaturaSeriNo, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.FaturaSıraNo)
    @Html.TextBoxFor(x => x.FaturaSıraNo, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.FaturaTarih)
    @Html.TextBoxFor(x => x.FaturaTarih, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Saat)
    @Html.TextBoxFor(x => x.Saat, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.VergiDairesi)
    @Html.TextBoxFor(x => x.VergiDairesi, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.TeslimEden)
    @Html.TextBoxFor(x => x.TeslimEden, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.TeslimAlan)
    @Html.TextBoxFor(x => x.TeslimAlan, new { @class = "form-control" })
    <br />
    <br />
    @Html.LabelFor(x => x.Toplam)
    @Html.TextBoxFor(x => x.Toplam, new { @class = "form-control" })

    <button class="btn btn-warning">Fatura Eklemeyi Onayla</button>
</form>

MVCOnlineTicariOtomasyon/Views/Fatura/FaturaGetir.cshtml
@model MVCOnlineTicariOtomasyon.Models.Sınıflar.Faturalar
@{
    ViewBag.Title = "FaturaGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    body {
        background-color: darkgray
    }
</style>
<br />
<h2 style="width=20px">Fatura Güncelleme Sayfası</h2>
<br />
@using (Html.BeginForm("FaturaGuncelle", "Fatura", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.FaturaID)
        @Html.LabelFor(x => x.FaturaSeriNo)
        @Html.TextBoxFor(x => x.FaturaSeriNo, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.FaturaSıraNo)
        @Html.TextBoxFor(x => x.FaturaSıraNo, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.VergiDairesi)
        @Html.TextBoxFor(x => x.VergiDairesi, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.FaturaTarih)
        @Html.TextBoxFor(x => x.FaturaTarih, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Saat)
        @Html.TextBoxFor(x => x.Saat, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.TeslimEden)
        @Html.TextBoxFor(x => x.TeslimEden, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.TeslimAlan)
        @Html.TextBoxFor(x => x.TeslimAlan, new { @class = "form-control" })
        <br />
        <br />
        <button class="btn btn-warning">Değişiklikleri kaydet</button>
    </div>
}

MVCOnlineTicariOtomasyon/Views/Fatura/Index.cshtml
@using MVCOnlineTicariOtomasyon.Models.Sınıflar;
@model List<Faturalar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    body {
        background-color: darkgray
    }
</style>
<br />
<h2>Fatura Listesi</h2>
<table id="tbl3" style="background-color: dimgray" class="table table-bordered">
    <thead>
        <tr>
            <th style="color:white">SERİ/SIRA NO</th>
            <th style="color:white">VERGİ DAİRESİ</th>
            <th style="color:white">TARİH</th>
            <th style="color:white">SAAT</th>
            <th style="color:white">TOPLAM</th>
            <th style="color:white">TESLİM EDEN</th>
            <th style="color:white">TESLİM ALAN</th>
            <th style="color:white">GÜNCELLE</th>
            <th style="color:white" width="50px">Detaylar</th>
        </tr>
    </thead>
    @foreach (var x in Model)
    {
<tr>
    <td style="color:black">
        @x.FaturaSeriNo @x.FaturaSıraNo
    </td>
    <td style="color:black">
        @x.VergiDairesi
    </td>
    <td style="color:black">
        @x.FaturaTarih
    </td>
    <td style="color:black">
        @x.Saat
    </td>
    <td style="color:black">
        100
    </td>
    <td style="color:black">
        @x.TeslimEden
    </td>
    <td style="color:black">
        @x.TeslimAlan
    </td>

    <td><a href="/Fatura/FaturaGetir/@x.FaturaID" class="btn btn-warning" style="color:white">Güncelle</a></td>

    <td style="color:white"><a href="/Fatura/FaturaDetay/@x.FaturaID" class="btn btn-default" style="background-color:lightcoral;color:white">Detaylar</a></td>
</tr>
    }
</table>
<a href="/Fatura/FaturaEkle" class="btn btn-primary">Yeni Fatura Giriş</a>



<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="~/Content/DataTables/css/dataTables.jqueryui.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>


<script>
    $('#tbl3').dataTable();
</script>

MVCOnlineTicariOtomasyon/Views/Fatura/YeniKalem.cshtml
@model MVCOnlineTicariOtomasyon.Models.Sınıflar.FaturaKalem
@{
    ViewBag.Title = "YeniKalem";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    body {
        background-color: darkgray
    }
</style>
<br />
<h2>Yeni Kalem Ekleme Alanı</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.Aciklama)
    @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Miktar)
    @Html.TextBoxFor(x => x.Miktar, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.BirimFiyat)
    @Html.TextBoxFor(x => x.BirimFiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Tutar)
    @Html.TextBoxFor(x => x.Tutar, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.FaturaID)
    @Html.TextBoxFor(x => x.FaturaID, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Fatura Eklemeyi Onayla</button>
</form>