MVCOnlineTicariOtomasyon/Controllers/SatisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCOnlineTicariOtomasyon.Models.Sınıflar;

namespace MVCOnlineTicariOtomasyon.Controllers
{
    public class SatisController : Controller
    {
        Context c = new Context();
        // GET: Satis
        public ActionResult Index()
        {
            var deger = c.SatisHarekets.Where(x=>x.Durum==true).ToList();
            return View(deger);
        }
        [HttpGet]
        public ActionResult YeniSatis()
        {
            List<SelectListItem> deger1 = (from x in c.Uruns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.UrunID.ToString()
                                           }).ToList();
            List<SelectListItem> deger2 = (from x in c.Carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAD + " " + x.CariSoyad,
                                               Value = x.CariID.ToString()
                                           }).ToList();
            List<SelectListItem> deger3 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.PersonelID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            return View();
        }

        [HttpPost]
        public ActionResult YeniSatis(SatisHareket s)
        {
            s.Durum = true;
            s.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            c.SatisHarekets.Add(s);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SatisGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Uruns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.UrunID.ToString()
                                           }).ToList();
            List<SelectListItem> deger2 = (from x in c.Carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAD + " " + x.CariSoyad,
                                               Value = x.CariID.ToString()
                                           }).ToList();
            List<SelectListItem> deger3 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.PersonelID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            var deger = c.SatisHarekets.Find(id);
            return View("SatisGetir", deger);
        }
        public ActionResult SatisGuncelle(SatisHareket s)
        {
            var urn = c.SatisHarekets.Find(s.SatisID);
            urn.Cariid = s.Cariid;
            urn.Adet = s.Adet;
            urn.Fiyat = s.Fiyat;
            urn.Personel_PersonelID = s.Personel_PersonelID;
            urn.Tarih = s.Tarih;
            urn.ToplamTutar = s.ToplamTutar;
            urn.Urunid = s.Urunid;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SatisDetay(int id)
        {
            var deger = c.SatisHarekets.Where(x => x.SatisID == id).ToList();
            return View(deger);
        }
        public ActionResult SatisSil(int id)
        {
           var deger= c.SatisHarekets.Find(id);
            deger.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVCOnlineTicariOtomasyon/Views/Satis/Index.cshtml
@using MVCOnlineTicariOtomasyon.Models.Sınıflar
@model List<SatisHareket>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    body {
        background-color: darkgray
    }
</style>
<br />
<h2>Satış Listesi</h2>
<table id="tbl6" style="background-color: dimgray" class="table table-bordered">
    <thead>
        <tr>
            <th style="color:white" width="60px" height="4px">ID</th>
            <th style="color:white">Ürün</th>
            <th style="color:white">Cari</th>
            <th style="color:white">Personel</th>
            <th style="color:white">Adet</th>
            <th style="color:white">Fiyat</th>
            <th style="color:white">Toplam</th>
            <th style="color:white">Tarih</th>
            <th style="color:white" width="50px">Sil</th>
            <th style="color:white" width="50px">Güncelle</th>
            <th style="color:white" width="120px">Detaylar</th>
        </tr>
    </thead>
    @foreach (var x in Model)
    {
<tr>
    <td style="color:black">
        @x.SatisID
    </td>
    <td style="color:black">
        @x.Urun.UrunAd
    </td>
    <td style="color:black">
        @x.Cariler.CariAD @x.Cariler.CariSoyad
    </td>
    <td style="color:black">
        @x.Personel.PersonelAd @x.Personel.PersonelSoyad
    </td>
    <td style="color:black">
        @x.Adet
    </td>
    <td style="color:black">
        @x.Fiyat
    </td>
    <td style="color:black">
        @x.ToplamTutar
    </td>
    <td style="color:black">
        @x.Tarih
    </td>

    <td style="color:white"><a href="/Satis/SatisSil/@x.SatisID" class="btn btn-danger">Sil</a></td>
    <td style="color:white"><a href="/Satis/SatisGetir/@x.SatisID" class="btn btn-warning">Güncelle</a></td>
    <td style="color:white"><a href="/Satis/SatisDetay/@x.SatisID" class="btn btn-default" style="background-color:lightcoral;color:white">Satışları Getir</a></td>
</tr>
    }
</table>
<a href="/Satis/YeniSatis" class="btn btn-primary">Yeni Satış Yap</a>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="~/Content/DataTables/css/dataTables.jqueryui.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>


<script>
    $('#tbl6').dataTable();
</script>

MVCOnlineTicariOtomasyon/Views/Satis/SatisDetay.cshtml
@using MVCOnlineTicariOtomasyon.Models.Sınıflar; 
@model List<SatisHareket>
@{
    ViewBag.Title = "SatisDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    body {
        background-color: darkgray
    }
</style>
<br />
<h2 style="font-style:oblique">Satış Ekranı</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active" style="font-style:oblique;font-display:block">Personel Adı: @ViewBag.dp</li>
</ol>
<br />
<table id="tbl8" class="table table-bordered" style="background-color: dimgray">
    <tr>
        <th>Satış ID</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.SatisID</td>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Cariler.CariAD @x.Cariler.CariSoyad</td>
            <td>@x.Personel.PersonelAd @x.Personel.PersonelSoyad</td>
            <td>@x.Fiyat</td>
            <td>@x.Adet</td>
            <td>@x.ToplamTutar</td>
            <td>@x.Tarih</td>
        </tr>
    }

</table>
<button class="btn btn-default" style="background-color:dodgerblue">Yazdır</button>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="~/Content/DataTables/css/dataTables.jqueryui.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>


<script>
    $('#tbl8').dataTable();
</script>

MVCOnlineTicariOtomasyon/Views/Satis/SatisGetir.cshtml
@model MVCOnlineTicariOtomasyon.Models.Sınıflar.SatisHareket
@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    body {
        background-color: darkgray
    }
</style>
<br />
<h2 style="width=20px">Satış İşlemi Güncelleme Sayfası</h2>
<br />
@using (Html.BeginForm("SatisGuncelle", "Satis", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.SatisID)
    @Html.LabelFor(x => x.SatisID)
    @Html.TextBoxFor(x => x.SatisID, new { @class = "form-control" })
    <br />
    @Html.Label("Ürün Seçiniz")
    @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.Label("Cari")
    @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.Label("Satış Yapan Personel")
    @Html.DropDownListFor(x => x.Personel_PersonelID, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Adet)
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Fiyat)
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ToplamTutar)
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Tarih)
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Değişiklikleri kaydet</button>
</div>
}

MVCOnlineTicariOtomasyon/Views/Satis/YeniSatis.cshtml
@model MVCOnlineTicariOtomasyon.Models.Sınıflar.SatisHareket
@{
    ViewBag.Title = "YeniSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    body {
        background-color: darkgray
    }
</style>
<br />
<h2>Yeni Ürün Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.Label("Ürün Seçiniz")
    @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.Label("Cari")
    @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.Label("Satış Yapan Personel")
    @Html.DropDownListFor(x => x.Personel_PersonelID, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Fiyat)
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Adet)
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ToplamTutar)
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    @*@Html.TextBoxFor(x => x.KategoriID, new { @class = "form-control" })*@
    <br />
    <button class="btn btn-warning">Satış Yap</button>
</form>