MVCOnlineTicariOtomasyon/Models/Sınıflar/Personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCOnlineTicariOtomasyon.Models.Sınıflar
{
    public class Personel
    {
        [Key]
        public int PersonelID { get; set; }

        [Display(Name ="Personel Adı")]
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelAd { get; set; }

        [Display(Name ="Personel Soyad")]
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelSoyad { get; set; }

        [Display(Name ="Görsel")]
        [Column(TypeName = "Varchar")]
        [StringLength(250)]
        public string PersonelGorsel { get; set; }
        public bool Durum { get; set; }

        public ICollection<SatisHareket> SatisHarekets { get; set; }
        public int Departmanid { get; set; }
        public virtual Departman Departman { get; set; }

    }
}

MVCOnlineTicariOtomasyon/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCOnlineTicariOtomasyon.Models.Sınıflar;

namespace MVCOnlineTicariOtomasyon.Controllers
{
    public class PersonelController : Controller
    {
        Context c = new Context();
        // GET: Personel
        public ActionResult Index()
        {
            var deger = c.Personels.Where(x => x.Durum == true).ToList();
            return View(deger);
        }
        public ActionResult PersonelGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Departmans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAD,
                                               Value = x.DepartmanID.ToString()
                                           }).ToList();
            ViewBag.dgr3 = deger1;
            var deger = c.Personels.Find(id);
            return View("PersonelGetir", deger);
        }
        public ActionResult PersonelSil(int id)
        {
            var deger = c.Personels.Find(id);
            deger.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult PersonelEkle()
        {
            List<SelectListItem> deger1 = (from x in c.Departmans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAD,
                                               Value = x.DepartmanID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger1;
            return View();
        }

        [HttpPost]
        public ActionResult PersonelEkle(Personel p)
        {
            p.Durum = true;
            c.Personels.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult PersonelGuncelle(Personel p1)
        {
            var deger = c.Personels.Find(p1.PersonelID);
            deger.PersonelAd = p1.PersonelAd;
            deger.PersonelSoyad = p1.PersonelSoyad;
            deger.PersonelGorsel = p1.PersonelGorsel;
            deger.Departmanid = p1.Departmanid;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult PersonelListe()
        {
            var deger = c.Personels.ToList();
            return View(deger);
        }
    }
}

MVCOnlineTicariOtomasyon/Views/Personel/Index.cshtml
@using MVCOnlineTicariOtomasyon.Models.Sınıflar
@model List<Personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    body {
        background-color: darkgray
    }
</style>
<br />
<h2>Personel Listesi</h2>
<table id="tbl5" style="background-color: dimgray" class="table table-bordered">
    <thead>
        <tr>
            <th style="color:white" width="60px" height="4px">ID</th>
            <th style="color:white">Görsel</th>
            <th style="color:white">Personel Ad</th>
            <th style="color:white"> Personel Soyad</th>
            <th style="color:white">Departman</th>
            <th style="color:white" width="50px">Sil</th>
            <th style="color:white" width="50px">Güncelle</th>
            <th style="color:white" width="120px">Satışlar</th>
        </tr>
    </thead>
    @foreach (var x in Model)
    {
<tr>
    <td style="color:black">
        @x.PersonelID
    </td>
    <td style="color:black">
        <img src="@x.PersonelGorsel" style="width:100px;height:80px" />
    </td>
    <td style="color:black">
        @x.PersonelAd
    </td>
    <td style="color:black">
        @x.PersonelSoyad
    </td>
    <td style="color:black">
        @x.Departman.DepartmanAD
    </td>

    <td style="color:white"><a href="/Personel/PersonelSil/@x.PersonelID" class="btn btn-danger">Sil</a></td>
    <td style="color:white"><a href="/Personel/PersonelGetir/@x.PersonelID" class="btn btn-warning">Güncelle</a></td>
    <td style="color:white"><a href="/Departman/DepartmanPersonelSatis/@x.PersonelID" class="btn btn-default" style="background-color:lightcoral;color:white">Satışları Getir</a></td>
</tr>
    }
</table>
<a href="/Personel/PersonelEkle" class="btn btn-primary">Personel Ekle</a>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="~/Content/DataTables/css/dataTables.jqueryui.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>


<script>
    $('#tbl5').dataTable();
</script>

MVCOnlineTicariOtomasyon/Views/Personel/PersonelEkle.cshtml
@model MVCOnlineTicariOtomasyon.Models.Sınıflar.Personel

@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<style>
    body {
        background-color: darkgray
    }
</style>
<br />
<h2>Personel Ekleme Alanı</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.PersonelAd)
    @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelSoyad)
    @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Departman)
    @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelGorsel)
    @Html.TextBoxFor(x => x.PersonelGorsel, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Kaydet</button>
</form>

MVCOnlineTicariOtomasyon/Views/Personel/PersonelGetir.cshtml
@model MVCOnlineTicariOtomasyon.Models.Sınıflar.Personel
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    body {
        background-color: darkgray
    }
</style>
<br />
<h2>Personel Güncelleme Alanı</h2>
<br />
@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(x => x.PersonelAd)
    @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelSoyad)
    @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Departman)
    @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelGorsel)
    @Html.TextBoxFor(x => x.PersonelGorsel, new { @class = "form-control" })
    <br />
    @Html.HiddenFor(x => x.PersonelID)
</div>
}
<button class="btn btn-warning">Kaydet</button>

MVCOnlineTicariOtomasyon/Views/Personel/PersonelListe.cshtml
@using MVCOnlineTicariOtomasyon.Models.Sınıflar
@model List<Personel>
@{
    ViewBag.Title = "PersonelListe";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Contacts</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Personel Detayları Sayfası</h1>
                    </div>

                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="card card-solid">
                <div class="card-body pb-0">
                    <div class="row d-flex align-items-stretch">
                        @foreach (var x in Model)
                        {
                            <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                                <div class="card bg-light">
                                    <div class="card-header text-muted border-bottom-0">
                                        @x.Departman.DepartmanAD
                                    </div>
                                    <div class="card-body pt-0">
                                        <div class="row">
                                            <div class="col-7">
                                                <h2 class="lead"><b>@x.PersonelAd @x.PersonelSoyad</b></h2>
                                                <p class="text-muted text-sm"><b>About: </b> Web Designer / UX / Graphic Artist / Coffee Lover </p>
                                                <ul class="ml-4 mb-0 fa-ul text-muted">
                                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                                                </ul>
                                            </div>
                                            <div class="col-5 text-center">
                                                <img src="@x.PersonelGorsel" alt="" class="img-circle img-fluid">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-footer">
                                        <div class="text-right">
                                            <a href="/Personel/PersonelGetir/@x.PersonelID" class="btn btn-sm bg-teal">
                                                <i class="fas fa-file-upload"></i>Personel Güncelle
                                            </a>
                                            <a href="/Departman/DepartmanPersonelSatis/@x.PersonelID" class="btn btn-sm btn-primary">
                                                <i class="fas fa-user"></i> Satış Geçmişi
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <!-- /.card -->

        </section>
        <!-- /.content -->
    </div>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../pluginsbootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="../../dist/js/demo.js"></script>
</body>
</html>